name: Play Variables
on:
  workflow_dispatch:

jobs:
  top-job:
    runs-on: ubuntu-24.04

    steps:
      - name: create foo var
        id: step1
        run: | 
          foo=barbarbar
          echo "straight after declaration ${foo}"
          echo "foo=${foo}" >> "$GITHUB_OUTPUT"
          
      - name: show variable from previ step
        run: |
          echo ${{ steps.step1.outputs.foo }}
    
